BBBB BBBBBB
XXXXXXXX
  XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX
        XXXXXXXX
      XXXX
      BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB        
        XXX XXXXXXXXXX  XXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXX              
            XX XXXXXXXXXXXXXXX BB BBBBBBBBB BB BBBBBBBBBBBB XXXXXX BBBBBX XXXXXXBBB BBBBBBBBBBBBXX
              XXXXX XXXXXXX
            XXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXX              
            XX XXXXXXXXXXXXXXX BB BBBBBBBBB BB BBBBBBBBBBBBB XXXXXX BBBBBX XXXXXXBBB BBBBBBBBBBBBBXX
              X XXXXXXX
            XXXX
          XXXXX
          XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX BB BBBBBBBBB BB BBBBBBBBBBBBB XXXXXX BBBBBX XXXXXXBBB BBBBBBBBBBBBBXX
              XXXX XXXXXXX
            XXXX
          XXXXX
        XXXXX
      BBBBBBB      
    XXXXXX
  XXXXXX 
XXXXXXXXX